### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by Christoph1111** [PaulW/rp2040-keyboard-converter#1]
Hi, how about using the "W" of the pico and add some bluetooth output?
Would be nice, using the keyboard for 3 computers without need of KVM.
Regards,

**Comment by PaulW** [comment]
This is something I considered originally when designing the internal adaptor for my F/AT keyboard, but at the moment with the work I'm doing towards multiple keyboard/protocol support & new hardware design for an inline converter, this isn't something I'm looking at implementing just yet.
