### ISSUE TITLE
Support Alt Gr

### ISSUE THREAD

**Issue by Christoph1111** [PaulW/rp2040-keyboard-converter#3]
Hi and thanks for this excellent work. How (and where) can I implement the german keyboard with AltGr Q = at, ALtGr E = Euro, AltGr (Bills Slash) = \ and AltGr + = ~ (Home)?

Regards

**Comment by PaulW** [comment]
Hi

So as I don't use these keys, I've set the keymap so AltGr is used as the Fn modifier, but you can change this by editing [src/keyboards/modelm/enhanced/keyboard.c](https://github.com/PaulW/rp2040-keyboard-converter/blob/main/src/keyboards/modelm/enhanced/keyboard.c) and changing `FN` to `RALT`, which should give you the functionality you need.  I also remap Right Control to `LGUI` (Windows/Command Key), so again if you need Right Control, you can substitute that to `RCTL` too if you wish.

One thing to note though, without the FN modifier in place, you'd lose some behaviour such as being able to force the RP2040 into Bootloader mode from pressing the Macro combination for this (FN + Left Shift + Right Shift + B).  But again, that's up to you (if you use the normal behaviour of holding BOOTSEL switch on whatever RP2040 is being used to allow you to upload any new firmware.
