### ISSUE TITLE
documentation issue :  docker-compose is depreciated.

### ISSUE THREAD

**Issue by lindoran** [PaulW/rp2040-keyboard-converter#5]
Just may need to update the build instruction see 2nd solution on Stack: 

https://stackoverflow.com/questions/68653051/using-docker-compose-without-sudo-doesnt-work

**Comment by PaulW** [comment]
Updated thanks! It's always something I end up missing...

https://github.com/PaulW/rp2040-keyboard-converter/commit/86b6c3b292fe7ce30f282f7df1501b127c33a5cd

**Comment by lindoran** [comment]
No worries - glad to help, you can't possibly keep up with everything all
the time fantastic project by the way!
